### PR TITLE
Pass usb-device tests, demonstrate USB ISR

### LINKED ISSUE #5: Example: polling in ISR
Provide an example that shows how to poll the USB device in a USB ISR. Implement all APIs to support this use-case.

### LINKED ISSUE #6: Pass the usb-device test suite
The `usb-device` crate provides a test class, and a host-side test suite, for evaluating a USB device implementation. Make sure we can pass the tests.

### PR DESCRIPTION
**Pull request by mciantyre**
The PR adds another Teensy 4 example that implements [a `usb-device` test class](https://docs.rs/usb-device/0.2.7/usb_device/test_class/index.html) USB device. Load this example onto your Teensy 4, and run the `usb-device` host-side test suite. You should see all the tests pass.

Bulk read and write benchmarks show around 1.8 Mbit/s in both directions. So either the test is broken, or there's room for improvement.

Closes #5, #6.

### CODE REVIEW

**Comment by mciantyre** [comment]
Draft until there's docs that say how to run the test suite.

**Comment by teburd** [comment]
Looking at the test case seems ok at first glance, do you have a stm32 device to try it against to compare? Do you have a logic analyzer you can use to measure timing of different sections with some pin flips? Like the ISR handling is a critical section that would effect speed I assume, how long is that really taking to run?

This nxp forum post seems relevant and shows throughput being higher at around 8Mbit/s or so for fullspeed (I noted you set the PFSC bitflag as they do).
https://community.nxp.com/t5/i-MX-Processors/IMXRT-USB-full-speed-example/td-p/872132

**Comment by mciantyre** [comment]
Good ideas! I don't have any other `usb-device` compatible hardware to get a baseline. I'll pull out my logic analyze when I'm ready to dig deep into optimization.

This test wasn't the best. There's at least two performance issues in the setup:

- Using XIP out of flash, when we could bring instructions closer to the processor.
- Pointing VTOR at flash. NXP says this is a no-no.

I went with the custom runtime to make the `imxrt-ral` feature selection explicit in the examples (and it grew organically from some other experimenting). This is opposed to the predefined `teensy4-bsp` crate, which doesn't make feature selection as obvious. Switching to the `teensy4-bsp` provides better performance, but looks like we can still tune more.

```
running 9 tests
test string_descriptors ... ok
test control_request ... ok
test control_data ... ok
test control_data_static ... ok
test control_error ... ok
test bulk_loopback ... ok
test interrupt_loopback ... ok
test bench_bulk_write ... ok
	16 transfers of 65536 bytes in 1.266s -> 6.628Mbit/s
test bench_bulk_read ... ok
	16 transfers of 65536 bytes in 1.176s -> 7.135Mbit/s
0 failed, 9 succeeded

ALL TESTS PASSED!
```

**Comment by teburd** [comment]
I'm glad you sorted out the issue, a vtor pointing at flash with xip makes a *lot* of sense as to why it was slower.

I keep hoping cortex-m-rt supports multiple memory regions and effectively supersedes what I was trying to do with imxrt-rt-gen, one can dream

**Comment by mciantyre** [comment]
It's kind of possible with today's `cortex-m-rt`. Nowadays the `teensy4-bsp` is using the stock `cortex-m-rt` runtime. We just need to write a `cortex-m-rt` compatible linker script. This also lets you override the reset handler to do what you need (like ITCM and DTCM setup).

Not sure if this is an endorsed `cortex-m-rt` usage, since they could change `cortex-m-rt` details to satisfy their bundled memory map, and treat that as a non-breaking change.

**Pull request merged**
