### PR TITLE
Set MSRV to 1.74; add CI check for it

### PR DESCRIPTION
**Pull request by Finomnis**
MSRV determined by running:

```none
$ cargo msrv --target=thumbv7em-none-eabihf
  [Meta]   cargo-msrv 0.16.0-beta.20                                                                                                                                                              

Compatibility Check #1: Rust 1.38.0
  [FAIL]   Is incompatible

  ╭────────────────────────────────────────────────────────────────────────╮
  │ error: failed to parse manifest at `D:\Projects\imxrt-usbd\Cargo.toml` │
  │                                                                        │
  │ Caused by:                                                             │
  │   invalid type: map, expected a string for key `package.edition`       │
  │                                                                        │
  ╰────────────────────────────────────────────────────────────────────────╯


Compatibility Check #2: Rust 1.58.1                                                                                                                                                               
  [FAIL]   Is incompatible

  ╭────────────────────────────────────────────────────────────────────────╮
  │ error: failed to parse manifest at `D:\Projects\imxrt-usbd\Cargo.toml` │
  │                                                                        │
  │ Caused by:                                                             │
  │   invalid type: map, expected a string for key `package.edition`       │
  │                                                                        │
  ╰────────────────────────────────────────────────────────────────────────╯


Compatibility Check #3: Rust 1.68.2                                                                                                                                                               
  [FAIL]   Is incompatible

  ╭──────────────────────────────────────────────────────────────────────────╮
  │     Checking imxrt-usbd v0.3.0 (D:\Projects\imxrt-usbd)                  │
  │ error[E0446]: crate-private type `Status` in public interface            │
  │    --> src\td.rs:69:5                                                    │
  │     |                                                                    │
  │ 69  |       pub fn status(&self) -> Status {                             │
  │     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type │
  │ ...                                                                      │
  │ 110 | / bitflags::bitflags! {                                            │
  │ 111 | |     pub(crate) struct Status : u32 {                             │
  │ 112 | |         const ACTIVE = TOKEN::STATUS::RW::ACTIVE;                │
  │ 113 | |         const HALTED = TOKEN::STATUS::RW::HALTED;                │
  │ ...   |                                                                  │
  │ 116 | |     }                                                            │
  │ 117 | | }                                                                │
  │     | |_- `Status` declared as crate-private                             │
  │                                                                          │
  │ For more information about this error, try `rustc --explain E0446`.      │
  │ error: could not compile `imxrt-usbd` due to previous error              │
  │                                                                          │
  ╰──────────────────────────────────────────────────────────────────────────╯


Compatibility Check #4: Rust 1.73.0                                                                                                                                                               
  [FAIL]   Is incompatible

  ╭──────────────────────────────────────────────────────────────────────────╮
  │     Checking imxrt-usbd v0.3.0 (D:\Projects\imxrt-usbd)                  │
  │ error[E0446]: crate-private type `Status` in public interface            │
  │    --> src\td.rs:69:5                                                    │
  │     |                                                                    │
  │ 69  |       pub fn status(&self) -> Status {                             │
  │     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type │
  │ ...                                                                      │
  │ 110 | / bitflags::bitflags! {                                            │
  │ 111 | |     pub(crate) struct Status : u32 {                             │
  │ 112 | |         const ACTIVE = TOKEN::STATUS::RW::ACTIVE;                │
  │ 113 | |         const HALTED = TOKEN::STATUS::RW::HALTED;                │
  │ ...   |                                                                  │
  │ 116 | |     }                                                            │
  │ 117 | | }                                                                │
  │     | |_- `Status` declared as crate-private                             │
  │                                                                          │
  │ For more information about this error, try `rustc --explain E0446`.      │
  │ error: could not compile `imxrt-usbd` (lib) due to previous error        │
  │                                                                          │
  ╰──────────────────────────────────────────────────────────────────────────╯


Compatibility Check #5: Rust 1.76.0                                                                                                                                                               
  [OK]     Is compatible

Compatibility Check #6: Rust 1.74.1                                                                                                                                                               
  [OK]     Is compatible

Result:
   Considered (min … max):   Rust 0.11.0 … Rust 1.78.0
   Search method:            bisect
   MSRV:                     1.74.1
   Target:                   thumbv7em-none-eabihf
 ```

### CODE REVIEW

**Comment by mciantyre** [comment]
I would be interested in adopting a MSRV throughout imxrt-rs packages. But I haven't done enough research to know how it works with dependencies.

For example, imxrt-usbd has an (optional) dependency on defmt. defmt [doesn't have a fixed MSRV policy](https://github.com/knurling-rs/defmt?tab=readme-ov-file#msrv). Suppose defmt incoporates a language feature requiring something greater than our 1.74 MSRV, and they publish a new 0.3 release. Wouldn't this new CI test start to fail once it pulls in that newer defmt version?

Generally, how can we guarantee a MSRV if the things we depend on do not guarantee an MSRV?

**Comment by Finomnis** [comment]
> I would be interested in adopting a MSRV throughout imxrt-rs packages. But I haven't done enough research to know how it works with dependencies.
> 
> For example, imxrt-usbd has an (optional) dependency on defmt. defmt [doesn't have a fixed MSRV policy](https://github.com/knurling-rs/defmt?tab=readme-ov-file#msrv). Suppose defmt incoporates a language feature requiring something greater than our 1.74 MSRV, and they publish a new 0.3 release. Wouldn't this new CI test start to fail once it pulls in that newer defmt version?
> 
> Generally, how can we guarantee a MSRV if the things we depend on do not guarantee an MSRV?

There's a discussion about [how much impact on a semver version an MSRV change should have](https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980/39). It's in general considered to not be a semver major change, from what I can see.

My opinion to that matter is the following:

If we checked that our `MSRV` works with the current dependencies, then there will always be a set of dependencies that once worked with that compiler version. So if a dependency breaks it, the user can always manually revert the dependency to an earlier version to get our project building again. The CI check makes sure that this is always possible.

I experienced that myself by being forced to Rust `1.56` through an old Rust Yocto layer at work, through which we had to build an `actix-web` based webserver. It officially supported this version via MSRV, but we had to revert a **lot** of dependencies to get it to build. But it worked in the end. And it seems that this way of handling things seems to be kind of the accepted way by the community.

So a little more formal; for me an MSRV means that our project, together with some set of dependency versions, work with the given MSRV. We break MSRV as soon as we force the user to update to a dependency version that breaks the MSRV. Which is exactly what the CI job checks.

**Comment by Finomnis** [comment]
Talking about `defmt` made me realize though that we should definitely enable all features for the MSRV. (imo)

**Comment by Finomnis** [comment]
Replaced by #28.

**Pull request closed without merging**
